# Define helper processes here. All of them would be spawned during
# `clio run` command execution.

# Running application binary
app:      ./application

# Running clio-watcher, which will track changes in .go and .template
# files and restart an application immediatelly.
# To use this tool, please make `go get github.com/cliohq/hot-swap`
hotswap:  clio-hotswap

# Example of embeding popular tools for UI development.
coffee:   coffee -c -w -o public/javascripts app/assets/javascripts
scss:     scss --watch app/assets/stylesheets:public/stylesheets --style compressed

# Please feel free to define any other processes here.
